# Generated by Django 3.2.6 on 2021-09-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
