# Generated by Django 3.2.6 on 2021-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
