# Generated by Django 3.2.6 on 2021-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='helper_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
