# Generated by Django 3.2.6 on 2021-09-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adoption',
            name='image_header_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
