# Generated by Django 3.2.6 on 2021-09-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_auto_20210920_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='adoption',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adoption.adoption'),
            preserve_default=False,
        ),
    ]
